
server:
  port: 8080


spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true




eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8000/eureka
#      defaultZone: http://eureka1:8000/eureka,http://eureka2:8001/eureka,http://eureka3:8002/eureka